kind: pipeline
name: default

#http://www.extentreports.com/docs/versions/5/klov/index.html

#version: '2'
#services:
#    klov:
#        image: anshooarora/klov:1.0.1
#        container_name: klov
#        environment:
#            - SPRING_DATA_MONGODB_URI=mongodb://172.29.1.77:27017
#        ports:
#            - 80:80



steps:
- name: Python&JavaforremoteIssue1
  image: carvk/java_python:openjdk15_python38
  #network_mode: host
  commands:
    - pip install -r requirements.txt
    - pytest -v -s

